# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0004_auto_20171021_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('destn', models.CharField(max_length=200)),
            ],
        ),
    ]
