# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
