# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-21 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0003_auto_20171021_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='name',
            new_name='tname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='uname',
        ),
    ]
