# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180413_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=50, unique=True)),
                ('filter', models.TextField(blank=True)),
                ('keys', models.CharField(blank=True, max_length=100)),
                ('window_length', models.IntegerField()),
                ('window_slide', models.IntegerField()),
                ('count_threshold', models.IntegerField()),
                ('current_job_id', models.CharField(max_length=200)),
            ],
        ),
    ]
