# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-28 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alertspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertspecification',
            name='flink_jar_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertspecification',
            name='current_job_id',
            field=models.TextField(),
        ),
    ]
