# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180428_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertspecification',
            name='jar_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
