# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='_NOT_PROVIDED_', max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='type',
            field=models.CharField(choices=[('neo4j', 'neo4j'), ('mongoDB', 'mongoDB'), ('postProcesing', 'postProcesing')], max_length=50),
        ),
    ]
