# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180531_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Query')),
            ],
        ),
        migrations.AddField(
            model_name='queryinput',
            name='attribute',
            field=models.CharField(default='_NOT_REQUIRED_', max_length=50),
        ),
    ]
