# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('destn', models.CharField(max_length=200)),
                ('bt', models.CharField(max_length=200)),
                ('et', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('hashtag', models.CharField(max_length=200)),
                ('retweet_of', models.CharField(max_length=200)),
                ('reply_of', models.CharField(max_length=200)),
                ('quoted', models.CharField(max_length=200)),
                ('has_mention', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
            ],
        ),
    ]
