# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postprocfunc_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.PostProcFunc')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Query')),
            ],
        ),
    ]
