# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_custommetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueryOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='type',
            field=models.CharField(choices=[('neo4j', 'neo4j'), ('mongoDB', 'mongoDB'), ('PostProcesing', 'PostProcesing')], default='neo4j', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queryoutput',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Query'),
        ),
        migrations.AddField(
            model_name='queryinput',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Query'),
        ),
    ]
