# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180531_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userscreenname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
